#!/usr/bin/env python

import sys
import jenkins
import urllib
import yaml
import subprocess
import os
from rospkg import environment
import optparse
import jenkins_tools

ubuntu = ['precise']
arch = ['amd64', 'i386']
param_names = ['UBUNTU_PARAM', 'ARCH_PARAM']
param_values = []
for u in ubuntu:
    for a in arch:
        param_values.append({'UBUNTU_PARAM': u, 'ARCH_PARAM': a})

# Schedule all devel jobs on Jenkins
def main():
    parser = optparse.OptionParser()
    parser.add_option("--name", action="store", default=None)
    (options, args) = parser.parse_args()
    if len(args) <= 3 or len(args)%2 != 0:
        print "Usage: %s email ros_distro [distro version]"%(sys.argv[0])
        sys.exit(0)

    email = args[0]
    ros_distro = args[1]
    script_args = args[2:]
    name = '-'.join(script_args)
    name = ros_distro+"-"+name
    if options.name:
        name = options.name + "-" + name
    if len(name) > 50:
        name = name[:48]+"..."
    script_args = [ros_distro] + script_args

    # create jenkins instance
    with open(os.path.join(environment.get_ros_home(), 'catkin-debs', 'server.yaml')) as f:
        info = yaml.load(f)
    jenkins_instance = jenkins.Jenkins(jenkins_tools.JENKINS_SERVER, info['username'], info['password'])

    # create all jobs
    job_name = jenkins_tools.run_jenkins_now(jenkins_instance, '$UBUNTU_PARAM', '$ARCH_PARAM', name, email,
                                             'prerelease', script_args, info['username'],
                                             param_names, param_values)
    jenkins_instance.build_job(job_name)

if __name__ == "__main__":
    main()
