#!/usr/bin/env python

import sys
import jenkins
import urllib
import yaml
import subprocess
import optparse
import os
from rospkg import environment
import jenkins_tools

ubuntus = {'fuerte': ['precise'],
           'groovy': ['precise']}
archs = ['amd64', 'i386']


# Schedule all devel jobs on Jenkins
def main():
    parser = optparse.OptionParser()
    (options, args) = parser.parse_args()

    if len(args) <= 2:
        print "Usage: %s email ros_distro [distribution]"%(sys.argv[0])
        sys.exit(0)
    email = args[0]
    ros_distro = args[1]
    repositories = args[2:]
    name = '-'.join(repositories)
    if len(name) > 30:
        name = name[:28]+"..."
    name = ros_distro+"-"+name
    script_args = ['--depends-on', ros_distro] + repositories
    
    # create jenkins instance 
    with open(os.path.join(environment.get_ros_home(), 'catkin-debs', 'server.yaml')) as f:
        info = yaml.load(f)
    jenkins_instance = jenkins.Jenkins('http://50.28.61.61:8080/', info['username'], info['password'])

    # create all jobs
    for ubuntu in ubuntus[ros_distro]:
        for arch in archs:
            job_name = jenkins_tools.run_jenkins_now(jenkins_instance, ubuntu, arch, name, email, 
                                                     'prerelease', script_args, info['username'])
            jenkins_instance.build_job(job_name)
            print "----"

if __name__ == "__main__":
    main()
